# Generated by Django 3.0.6 on 2020-05-24 05:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_id', models.IntegerField()),
                ('dt_name', models.CharField(max_length=20)),
                ('dt_location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_roll', models.IntegerField()),
                ('st_name', models.CharField(max_length=20)),
                ('st_sub', models.CharField(max_length=20)),
                ('st_join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('st_did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Department')),
            ],
        ),
    ]
